name: File Size Report

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  pkg-size-report:
    name: File Size Report
    runs-on: ubuntu-latest

    steps:
      - name: compressed-size-action
        uses: preactjs/compressed-size-action@2.5.0
