name: test

on: [push]

jobs:
  pkg-size-report:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' 
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test